### ISSUE TITLE
Failed to link to native library error

### ISSUE THREAD

**Issue by funtowrite** [arodchen/MaxSim#2]
Hi, I've been trying to get maxine to work with Cassandra-2.2.0 and Voldemort-1.9.0, but I keep running into different errors. Could you please help me? 

For Cassandra, the error and stack trace that I get is: 
------ Cause Exception ------java.lang.ClassNotFoundException: org.hyperic.sigar.FileSystem
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.sun.max.vm.jni.JniFunctions.findClass(JniFunctions.java:383)
	at com.sun.max.vm.jni.JniFunctions.FindClass(JniFunctions.java:404)
	at org.hyperic.sigar.Sigar.getFileSystemListNative(Native Method)
	at org.hyperic.sigar.Sigar.getFileSystemList(Sigar.java:650)
	at org.hyperic.sigar.Sigar.getFileSystemMap(Sigar.java:722)
	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:48)
	at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
	at com.sun.max.vm.actor.member.MethodActor.invoke(MethodActor.java:418)
	at com.sun.max.vm.actor.holder.ClassActor.callInitializer(ClassActor.java:1560)
	at com.sun.max.vm.actor.holder.ClassActor.makeInitialized(ClassActor.java:1664)
	at com.sun.max.vm.runtime.Snippets.makeClassInitialized(Snippets.java:444)
	at com.sun.max.vm.runtime.Snippets.makeHolderInitialized(Snippets.java:433)
	at com.oracle.max.vm.ext.t1x.T1XTemplateSource.resolveAndGetStaticReference(T1XTemplateSource.java:1707)
	at org.apache.cassandra.service.StartupChecks$6.execute(StartupChecks.java:198)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:107)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:168)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:533)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:642)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.max.vm.run.java.JavaRunScheme.lookupAndInvokeMain(JavaRunScheme.java:376)
	at com.sun.max.vm.run.java.JavaRunScheme.run(JavaRunScheme.java:333)
	at com.sun.max.vm.thread.VmThread.executeRunnable(VmThread.java:511)
	at com.sun.max.vm.thread.VmThread.run(VmThread.java:682)

For Voldemort, I'm getting the following error: 
[14:00:18,873 voldemort.utils.JNAUtils] INFO Failed to link to native library [main]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Java_voldemort_utils_JNAUtils_mlockall __I
	at com.sun.max.vm.jni.DynamicLinker.lookup(DynamicLinker.java:271)
	at com.sun.max.vm.actor.member.NativeFunction.link0(NativeFunction.java:117)
	at com.sun.max.vm.actor.member.NativeFunction.link(NativeFunction.java:110)
	at voldemort.utils.JNAUtils.mlockall(Native Method)
	at voldemort.utils.JNAUtils.tryMlockall(JNAUtils.java:51)
	at voldemort.server.VoldemortServer.startInner(VoldemortServer.java:328)
	at voldemort.common.service.AbstractService.start(AbstractService.java:62)
	at voldemort.server.VoldemortServer.main(VoldemortServer.java:384)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.max.vm.run.java.JavaRunScheme.lookupAndInvokeMain(JavaRunScheme.java:376)
	at com.sun.max.vm.run.java.JavaRunScheme.run(JavaRunScheme.java:333)
	at com.sun.max.vm.thread.VmThread.executeRunnable(VmThread.java:511)
	at com.sun.max.vm.thread.VmThread.run(VmThread.java:682)

Thank you!

**Comment by kotselidis** [comment]
Hi,

It appears that this bug is not MaxSim related, but it's due to Maxine VM.
I suggest trying your applications with the latest Maxine VM release at: https://github.com/beehive-lab/Maxine-VM/
and if the bug persists then fill an issue on that repository.
It would be great if you could also provide your setup configuration.

Thanks
